version: '3.8'

services:
  streamlit:
    build: .
    container_name: streamlit_app
    restart: always
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
    ports:
      - "8501:8501"
    volumes:
      - ./master project mapping.xlsx:/app/master project mapping.xlsx